# Generated by Django 5.1.6 on 2025-02-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='club_pfps/'),
        ),
    ]
