# Generated by Django 5.1.6 on 2025-02-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='17:00:00'),
        ),
    ]
