# Generated by Django 5.1.6 on 2025-02-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_authentication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
