# Generated by Django 5.1.6 on 2025-04-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_club_account_alter_club_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='pfp',
            field=models.ImageField(blank=True, default='defaultpfp.png', null=True, upload_to='club_pfps/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='defaultevent.png', null=True, upload_to='event_images/'),
        ),
    ]
